[2024-09-01T14:00:30.814+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-01T14:00:31.513+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Apriori_project.branch_task scheduled__2024-08-31T00:00:00+00:00 [queued]>
[2024-09-01T14:00:31.542+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Apriori_project.branch_task scheduled__2024-08-31T00:00:00+00:00 [queued]>
[2024-09-01T14:00:31.545+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-01T14:00:31.592+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2024-08-31 00:00:00+00:00
[2024-09-01T14:00:31.608+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=7625) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-01T14:00:31.613+0000] {standard_task_runner.py:64} INFO - Started process 7637 to run task
[2024-09-01T14:00:31.615+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Apriori_project', 'branch_task', 'scheduled__2024-08-31T00:00:00+00:00', '--job-id', '404', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpazb_b34a']
[2024-09-01T14:00:31.624+0000] {standard_task_runner.py:91} INFO - Job 404: Subtask branch_task
[2024-09-01T14:00:31.757+0000] {task_command.py:426} INFO - Running <TaskInstance: Apriori_project.branch_task scheduled__2024-08-31T00:00:00+00:00 [running]> on host 19bb8daff211
[2024-09-01T14:00:32.105+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Apriori_project' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-31T00:00:00+00:00'
[2024-09-01T14:00:32.111+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-01T14:00:32.164+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-09-01T14:00:32.204+0000] {python.py:237} INFO - Done. Returned value was: processing_data
[2024-09-01T14:00:32.205+0000] {branch.py:36} INFO - Branch into processing_data
[2024-09-01T14:00:32.207+0000] {skipmixin.py:178} INFO - Following branch processing_data
[2024-09-01T14:00:32.270+0000] {skipmixin.py:246} INFO - Skipping tasks []
[2024-09-01T14:00:32.307+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-01T14:00:32.360+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Apriori_project, task_id=branch_task, run_id=scheduled__2024-08-31T00:00:00+00:00, execution_date=20240831T000000, start_date=20240901T140031, end_date=20240901T140032
[2024-09-01T14:00:32.440+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-01T14:00:32.545+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-01T14:00:32.551+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
