[2024-09-01T11:02:46.729+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-01T11:02:47.014+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_dag.start_task manual__2024-09-01T11:02:44.401588+00:00 [queued]>
[2024-09-01T11:02:47.025+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_dag.start_task manual__2024-09-01T11:02:44.401588+00:00 [queued]>
[2024-09-01T11:02:47.026+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-01T11:02:47.047+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): start_task> on 2024-09-01 11:02:44.401588+00:00
[2024-09-01T11:02:47.057+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_dag', 'start_task', 'manual__2024-09-01T11:02:44.401588+00:00', '--job-id', '383', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmphzbu7ns0']
[2024-09-01T11:02:47.055+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=6554) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-01T11:02:47.062+0000] {standard_task_runner.py:91} INFO - Job 383: Subtask start_task
[2024-09-01T11:02:47.062+0000] {standard_task_runner.py:64} INFO - Started process 6556 to run task
[2024-09-01T11:02:47.128+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_dag.start_task manual__2024-09-01T11:02:44.401588+00:00 [running]> on host 19bb8daff211
[2024-09-01T11:02:47.262+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='jorgepons90@gmail.com,facturasjorgepons@gmail.com' AIRFLOW_CTX_DAG_OWNER='Jorge Pons' AIRFLOW_CTX_DAG_ID='simple_dag' AIRFLOW_CTX_TASK_ID='start_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T11:02:44.401588+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-01T11:02:44.401588+00:00'
[2024-09-01T11:02:47.265+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-01T11:02:47.309+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-01T11:02:47.310+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-01T11:02:47.323+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=simple_dag, task_id=start_task, run_id=manual__2024-09-01T11:02:44.401588+00:00, execution_date=20240901T110244, start_date=20240901T110247, end_date=20240901T110247
[2024-09-01T11:02:47.360+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-01T11:02:47.403+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-01T11:02:47.406+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
