[2024-09-01T10:45:10.360+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-01T10:45:10.637+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_dag.get_data manual__2024-09-01T10:45:05.574626+00:00 [queued]>
[2024-09-01T10:45:10.652+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_dag.get_data manual__2024-09-01T10:45:05.574626+00:00 [queued]>
[2024-09-01T10:45:10.656+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-01T10:45:10.680+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_data> on 2024-09-01 10:45:05.574626+00:00
[2024-09-01T10:45:10.691+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=6311) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-01T10:45:10.693+0000] {standard_task_runner.py:64} INFO - Started process 6313 to run task
[2024-09-01T10:45:10.694+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_dag', 'get_data', 'manual__2024-09-01T10:45:05.574626+00:00', '--job-id', '377', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp219xpyl_']
[2024-09-01T10:45:10.697+0000] {standard_task_runner.py:91} INFO - Job 377: Subtask get_data
[2024-09-01T10:45:10.768+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_dag.get_data manual__2024-09-01T10:45:05.574626+00:00 [running]> on host 19bb8daff211
[2024-09-01T10:45:10.913+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='jorgepons90@gmail.com,facturasjorgepons@gmail.com' AIRFLOW_CTX_DAG_OWNER='Jorge Pons' AIRFLOW_CTX_DAG_ID='simple_dag' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T10:45:05.574626+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-01T10:45:05.574626+00:00'
[2024-09-01T10:45:10.915+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-01T10:45:10.978+0000] {base.py:84} INFO - Using connection ID 'my_mssql_conn_id' for task execution.
[2024-09-01T10:45:11.027+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-01T10:45:11.029+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-01T10:45:11.044+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=simple_dag, task_id=get_data, run_id=manual__2024-09-01T10:45:05.574626+00:00, execution_date=20240901T104505, start_date=20240901T104510, end_date=20240901T104511
[2024-09-01T10:45:11.110+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-01T10:45:11.151+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-01T10:45:11.155+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
